---
- hosts: 127.0.0.1
  sudo: yes
  vars:
    - ruby_version: 2.0.0-p195
  tasks:
    - name: apt-get update
      apt: update_cache=yes
    - name: apt-get upgrade
      apt: upgrade=full
    #- name: apt-get install git
    #  apt: name=git state=latest
    #- name: disable iptables
    #  service: name=iptables state=stopped enabled=no
    #- name: install libselinux-python
    #  apt: name=libselinux-python state=latest

    - name: remove localtime
      file: path=/etc/localtime state=absent
    - name: change timezone
      file: src=/usr/share/zoneinfo/Asia/Tokyo dest=/etc/localtime state=link force=yes mode=0644

    - name: install apache
      apt: name=apache2 state=latest
    - name: start apache and enabled
      service: name=apache2 state=started enabled=yes
    - name: change owner
      file: dest=/var/www/html owner=vagrant recurse=yes

    - name: install php
      apt: name={{item}} state=latest
      with_items:
        - php5-common
        - libapache2-mod-php5
        - php5-cli
        - php5-dev
        - php5-mysql
        - php5-gd
      notify:
        - restart apache
    - name: copy php.ini.yamao2253
      copy: src=php.ini.yamao2253 dest=/etc/php.ini backup=yes
      notify:
        - restart apache

    - name: install mysql
      apt: name=mysql-server state=present
    - name: copy my.cnf.yamao2253
      copy: src=my.cnf.yamao2253 dest=/etc/my.cnf backup=yes
    - name: start mysql and enabled
      service: name=mysql state=started enabled=yes

    - name: install ruby dependencies
      apt: name={{item}} state=present
      with_items:
        - autoconf 
        - bison 
        - build-essential 
        - libssl-dev 
        - libyaml-dev 
        - libreadline6-dev 
        - zlib1g-dev 
        - libncurses5-dev 
        - libffi-dev 
        - libgdbm3 
        - libgdbm-dev

    - name: check rbenv installed
      command: test -x /home/vagrant/.rbenv
      register: rbenv_present
      ignore_errors: yes
      sudo: no
    - name: git clone rbenv
      git: repo=https://github.com/sstephenson/rbenv.git dest=/home/vagrant/.rbenv
      when: rbenv_present.rc != 0
      sudo: no
    - name: update bash_profile
      copy: src=bash_profile.custom dest=/home/vagrant/.bash_profile backup=yes
      sudo: no 

    - name: check ruby-build installed
      command: test -x /home/vagrant/.rbenv/plugins/ruby-build
      register: rbuild_present
      ignore_errors: yes
      sudo: no
    - name: git clone ruby-build
      git: repo=https://github.com/sstephenson/ruby-build.git dest=/home/vagrant/.rbenv/plugins/ruby-build
      when: rbuild_present.rc != 0
      sudo: no

    #- name: source bash_profile
    #  command: source /home/vagrant/.bash_profile
    #  sudo: no

    - name: check ruby installed
      shell: /bin/bash -lc "rbenv versions | grep {{ruby_version}}"
      register: ruby_installed
      ignore_errors: yes
      sudo: no
    - name: install ruby
      shell: /bin/bash -lc "CONFIGURE_OPTS=--with-readline-dir="/usr/lib/x86_64-linux-gnu/libreadline.so" rbenv install {{ruby_version}} && rbenv rehash && rbenv global {{ruby_version}}"
      when: ruby_installed.rc != 0
      sudo: no

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
