---
- hosts: 127.0.0.1
  sudo: yes
  vars:
    - ruby_version: 2.2.0
    - rbenv_configure_opts: --disable-install-rdoc --with-readline-dir="/usr/lib/x86_64-linux-gnu/libreadline.so"
  tasks:
    - name: apt-get update
      apt: update_cache=yes
    - name: apt-get upgrade
      apt: upgrade=full

    - name: remove localtime
      file: path=/etc/localtime state=absent
    - name: change timezone
      file: src=/usr/share/zoneinfo/Asia/Tokyo dest=/etc/localtime state=link force=yes mode=0644

    - name: install apache
      apt: name=apache2 state=latest
    - name: start apache and enabled
      service: name=apache2 state=started enabled=yes
    - name: change owner
      file: dest=/var/www/html owner=vagrant recurse=yes

    - name: install php
      apt: name={{item}} state=latest
      with_items:
        - php5-common
        - libapache2-mod-php5
        - php5-cli
        - php5-dev
        - php5-mysql
        - php5-gd
      notify:
        - restart apache
    - name: copy php.ini.yamao2253
      copy: src=php.ini.yamao2253 dest=/etc/php.ini backup=yes
      notify:
        - restart apache

    - name: install mysql
      apt: name=mysql-server state=present
    - name: copy my.cnf.yamao2253
      copy: src=my.cnf.yamao2253 dest=/etc/my.cnf backup=yes
    - name: start mysql and enabled
      service: name=mysql state=started enabled=yes

    - name: install ruby dependencies
      apt: name={{item}} state=present
      with_items:
        - curl
        - g++
        - libreadline-dev
        - libxml2-dev
        - libxslt-dev
        - sqlite3
        - libsqlite3-dev
        - nodejs
        - zlib1g-dev 
        - libssl-dev
        - libyaml-dev
        - libffi-dev 

    - name: check rbenv installed
      command: test -x /home/vagrant/.rbenv
      register: rbenv_present
      ignore_errors: yes
      sudo: no
    - name: git clone rbenv
      git: repo=https://github.com/sstephenson/rbenv.git dest=/home/vagrant/.rbenv
      when: rbenv_present.rc != 0
      sudo: no
    - name: update bash_profile
      copy: src=bash_profile.custom dest=/home/vagrant/.bash_profile backup=yes
      sudo: no 

    - name: check ruby-build installed
      command: test -x /home/vagrant/.rbenv/plugins/ruby-build
      register: rbuild_present
      ignore_errors: yes
      sudo: no
    - name: git clone ruby-build
      git: repo=https://github.com/sstephenson/ruby-build.git dest=/home/vagrant/.rbenv/plugins/ruby-build
      when: rbuild_present.rc != 0
      sudo: no

    - name: check ruby installed
      shell: /bin/bash -lc "rbenv versions | grep {{ruby_version}}"
      register: ruby_installed
      #ignore_errors: yes
      failed_when: ruby_installed.rc not in [0, 1]
      sudo: no

    - debug: msg="ruby_installed={{ ruby_installed.stderr }}"
    - debug: msg="ruby_installed.rc={{ ruby_installed.rc.stderr }}"

    - name: install ruby
      shell: /bin/bash -lc "CONFIGURE_OPTS="{{rbenv_configure_opts}}" rbenv install {{ruby_version}} && rbenv rehash && rbenv global {{ruby_version}}"
      #shell: /bin/bash -lc "rbenv install {{ruby_version}} && rbenv rehash && rbenv global {{ruby_version}}"
      when: ruby_installed.rc != 0
      sudo: no
      poll: 60
      async: 1200

    - name: check node js installed
      shell: /bin/bash -lc "node -v"
      register: node_installed
      ignore_errors: yes
      sudo: no
    - name: install node script
      shell: /bin/bash -lc "curl -sL https://deb.nodesource.com/setup | bash -"
      when: node_installed.rc != 0
    - name: install nodejs
      apt: name=nodejs state=latest
      when: node_installed.rc != 0
    #- name: install nodejs (ppa)
    #  apt_repository: repo='ppa:chris-lea/node.js'

    - name: Rename from nodojs to node utilizing update-alternatives
      command: update-alternatives --install /usr/bin/node node /usr/bin/nodejs 10

    - name: gem install modules for sinatra
      gem: name={{item}} state=latest
      with_items:
        - activerecord
        - libsqlite3-dev
        - sqlite3
        - sinatra
        - sinatra-contrib

    # - name: gem install activerecord
    #   gem: name=activerecord state=latest
    #   sudo: no

    # - name: gem preparation of sqlite3 install(libsqlite3-dev)
    #   apt: name=libsqlite3-dev state=present

    # - name: gem install sqlite3
    #   gem: name=sqlite3 state=latest
    #   sudo: no

    # - name: gem install sinatra
    #   gem: name=sinatra state=latest
    #   sudo: no

    # - name: gem install sinatra-contrib
    #   gem: name=sinatra-contrib state=latest
    #   sudo: no
   

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
