---
- hosts: 127.0.0.1
  sudo: yes
  vars:
    - ruby_version: 2.2.0
  tasks:
    - name: apt-get update
      apt: update_cache=yes
    - name: apt-get upgrade
      apt: upgrade=full
    #- name: apt-get install git
    #  apt: name=git state=latest
    #- name: disable iptables
    #  service: name=iptables state=stopped enabled=no
    #- name: install libselinux-python
    #  apt: name=libselinux-python state=latest

    - name: remove localtime
      file: path=/etc/localtime state=absent
    - name: change timezone
      file: src=/usr/share/zoneinfo/Asia/Tokyo dest=/etc/localtime state=link force=yes mode=0644

    - name: install apache
      apt: name=apache2 state=latest
    - name: start apache and enabled
      service: name=apache2 state=started enabled=yes
    - name: change owner
      file: dest=/var/www/html owner=vagrant recurse=yes

    - name: install php
      apt: name={{item}} state=latest
      with_items:
        - php5-common
        - libapache2-mod-php5
        - php5-cli
        - php5-dev
        - php5-mysql
        - php5-gd
      notify:
        - restart apache
    - name: copy php.ini.yamao2253
      copy: src=php.ini.yamao2253 dest=/etc/php.ini backup=yes
      notify:
        - restart apache

    - name: install mysql
      apt: name=mysql-server state=present
    - name: copy my.cnf.yamao2253
      copy: src=my.cnf.yamao2253 dest=/etc/my.cnf backup=yes
    - name: start mysql and enabled
      service: name=mysql state=started enabled=yes

    - name: install ruby dependencies
      apt: name={{item}} enablerepo=remi,epel state=present
      with_items:
        - gcc
        - libssl-dev
        - build-essential
        - bzip2
        - libtool
        - zlib
        - zlib1g-dev
        - apache2-dev
        - libcurl4-openssl-dev
        - libncurses5-dev
        - libgdbm-dev
        - libreadline6
        - libreadline6-dev
        - libsqlite3-dev
        - libyaml-dev
        - libffi-dev
        - bison

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
